import Head from "next/head";
import Image from "next/image";
import React from "react";
import styles from "@/styles/Home.module.css";
import { LinkBox, Box, Heading, LinkOverlay, Text } from "@chakra-ui/react";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <LinkBox
            as="article"
            maxW="sm"
            p="5"
            borderWidth="1px"
            rounded="md"
            borderRadius="10px"
            title="This card is built using Chakra-UI"
            _hover={{
              color: "#0070f3",
              borderColor: "#0070f3",
            }}
          >
            <Text as="h2" fontSize="1.5rem" mb="1rem">
              <LinkOverlay href="https://nextjs.org/docs">
                Documentation &rarr;
              </LinkOverlay>
            </Text>
            <Text fontSize="1.25rem" lineHeight="1.5">
              Find in-depth information about Next.js features and API.
            </Text>
          </LinkBox>

          <a
            href="https://nextjs.org/learn"
            className={styles.card}
            title="This card is built using Custom CSS"
          >
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
            title="This card is built using Custom CSS"
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            title="This card is built using Custom CSS"
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
